steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/high-income-prediction-image', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'high-income-prediction-image', '--image', 'gcr.io/$PROJECT_ID/high-income-prediction-image', '--region', 'us-central1']
images:
- 'gcr.io/$PROJECT_ID/high-income-prediction-image'